name: Update data

#on: workflow_dispatch
on:
  schedule:
    - cron: 45 11 * * * # 6:45 PM in Vietnam
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repo and sub module
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Init and update submodules
        run: |
         git submodule sync
         git submodule update --init --recursive
         
      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: pip
          cache-dependency-path: requirements.txt
      
      - name: install python packages
        run: |
          pip install -r requirements.txt
          pip install -r vietnam-lottery-xsmb-analysis/requirements.txt

      - name: fetch data
        run: python fetch.py

      - name: train model
        run: python lottery_prediction_model.py

      - name: predict data
        run: python predict_255_unique_from_model.py
      
      - name: update readme
        run: python update_readme.py

      - name: get current date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: push changes
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          message: Updated ${{ env.date }}
          email: action@github.com
          name: GitHub Action
