name: Update data

on:
  workflow_dispatch: # Chỉ cần sự kiện này là đủ để cho phép gọi từ API hoặc bấm tay

jobs:
  update-data:
    runs-on: ubuntu-24.04
    steps:
      - name: Dummy Test Step
        run: |
          echo "=================================================="
          echo "SUCCESS: Workflow 2 is triggered automatically!"
          echo "=================================================="
